services:

  db:
    container_name: postgres
    image: postgres:15.1
    environment:
        POSTGRES_USER: aurickcode
        POSTGRES_PASSWORD: aurickpassword
        PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped

  # aurickcode-api:
  #   container_name: aurickcode-api
  #   image: anurodh1/aurickcode-api:0.0.1-SNAPSHOT
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/customer
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - db
  #   depends_on:
  #     - db
  #   restart: unless-stopped

  # aurickcode-react:
  #   container_name: aurickcode-react
  #   image: anurodh1/aurickcode-react
  #   build:
  #     context: frontend/react
  #     args:
  #       api_base_url: http://localhost:8080
  #   ports:
  #     - "3000:5173"
  #   depends_on:
  #     - aurickcode-api
  #   restart: unless-stopped

networks:
  db:
    driver: bridge
  
volumes:
  db: